version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=datting
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./database:/home
volumes:
  redis_volume:
  mysql_volume: