// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Crypt is an autogenerated mock type for the Crypt type
type Crypt struct {
	mock.Mock
}

// HashString provides a mock function with given fields: str
func (_m *Crypt) HashString(str string) (string, error) {
	ret := _m.Called(str)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(str)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(str)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(str)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VerifyHash provides a mock function with given fields: strHash, plainText
func (_m *Crypt) VerifyHash(strHash string, plainText string) bool {
	ret := _m.Called(strHash, plainText)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(strHash, plainText)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewCrypt interface {
	mock.TestingT
	Cleanup(func())
}

// NewCrypt creates a new instance of Crypt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCrypt(t mockConstructorTestingTNewCrypt) *Crypt {
	mock := &Crypt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
